// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Runtira.Infrastructure.Data;

#nullable disable

namespace Runtira.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260703183533_SyncRuntiraSchemaAfterTypedPayloads")]
    partial class SyncRuntiraSchemaAfterTypedPayloads
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LegalProfileJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnitCount")
                        .HasColumnType("int");

                    b.Property<string>("WorkflowSummaryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RuntiraAssets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-bbbb-cccc-222222222222"),
                            AdditionalDataJson = "{\"source\":\"seed\"}",
                            AddressLine1 = "1180 17 Ave SW",
                            AssetType = "Property",
                            City = "Calgary",
                            CountryCode = "CA",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LegalProfileJson = "{\"requiredQuestions\":[\"address\",\"period\",\"monthlyRent\"]}",
                            Name = "1180 17 Ave SW",
                            RegionCode = "AB",
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb"),
                            UnitCount = 12,
                            WorkflowSummaryJson = "{\"status\":\"ready\"}"
                        },
                        new
                        {
                            Id = new Guid("13131313-aaaa-bbbb-cccc-242424242424"),
                            AdditionalDataJson = "{\"source\":\"seed\"}",
                            AddressLine1 = "25 Carlton Street",
                            AssetType = "Property",
                            City = "Toronto",
                            CountryCode = "CA",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LegalProfileJson = "{\"requiredQuestions\":[\"propertyAddress\",\"billingPeriod\",\"tenantName\",\"monthlyRent\"]}",
                            Name = "25 Carlton Street",
                            RegionCode = "ON",
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc"),
                            UnitCount = 20,
                            WorkflowSummaryJson = "{\"status\":\"ready\"}"
                        },
                        new
                        {
                            Id = new Guid("15151515-aaaa-bbbb-cccc-262626262626"),
                            AdditionalDataJson = "{\"source\":\"seed\"}",
                            AddressLine1 = "2400 McKinney Avenue",
                            AssetType = "Property",
                            City = "Dallas",
                            CountryCode = "US",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LegalProfileJson = "{\"requiredQuestions\":[\"propertyAddress\",\"billingPeriod\",\"ownerName\",\"monthlyRent\"]}",
                            Name = "2400 McKinney Avenue",
                            RegionCode = "TX",
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd"),
                            UnitCount = 18,
                            WorkflowSummaryJson = "{\"status\":\"ready\"}"
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlobArchiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InboxMessageId");

                    b.ToTable("RuntiraAttachments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68686868-aaaa-bbbb-cccc-909090909091"),
                            Category = "LeadDocument",
                            ContentType = "text/plain",
                            CreatedUtc = new DateTime(2026, 7, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "budget-range.txt",
                            InboxMessageId = new Guid("62626262-aaaa-bbbb-cccc-848484848484"),
                            MetadataJson = "{\"source\":\"mock-inbox\"}",
                            SizeBytes = 256L,
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("70707070-aaaa-bbbb-cccc-929292929293"),
                            Category = "VendorQuote",
                            ContentType = "application/pdf",
                            CreatedUtc = new DateTime(2026, 7, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "vendor-quote.pdf",
                            InboxMessageId = new Guid("66666666-aaaa-bbbb-cccc-888888888889"),
                            MetadataJson = "{\"source\":\"mock-inbox\"}",
                            SizeBytes = 40960L,
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd")
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraBlobArchive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RuntiraBlobArchives");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-aaaa-bbbb-cccc-000000000000"),
                            BlobPath = "demo-alberta/invoices/2026/07/invoice-july.json",
                            Category = "InvoiceDraft",
                            ContentType = "application/json",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hash = "seed-demo-alberta-invoice",
                            MetadataJson = "{\"period\":\"2026-07\"}",
                            SizeBytes = 512L,
                            SourceSystem = "seed",
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-aaaa-bbbb-cccc-020202020202"),
                            BlobPath = "demo-ontario/invoices/2026/07/invoice-july.json",
                            Category = "InvoiceDraft",
                            ContentType = "application/json",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hash = "seed-demo-ontario-invoice",
                            MetadataJson = "{\"period\":\"2026-07\"}",
                            SizeBytes = 544L,
                            SourceSystem = "seed",
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc")
                        },
                        new
                        {
                            Id = new Guid("a3a3a3a3-aaaa-bbbb-cccc-040404040404"),
                            BlobPath = "demo-texas/invoices/2026/07/invoice-july.json",
                            Category = "InvoiceDraft",
                            ContentType = "application/json",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Hash = "seed-demo-texas-invoice",
                            MetadataJson = "{\"period\":\"2026-07\"}",
                            SizeBytes = 536L,
                            SourceSystem = "seed",
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd")
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JurisdictionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastMessageUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RuntiraConversations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-aaaa-bbbb-cccc-444444444444"),
                            Channel = "Chat",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Intent = "CreateInvoice",
                            JurisdictionCode = "CA-AB",
                            LastMessageUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Locale = "fr-CA",
                            Status = "Open",
                            Subject = "Créer une facture mensuelle Alberta",
                            SummaryJson = "{\"nextQuestion\":\"Quel mois doit apparaître sur la facture PDF ?\"}",
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("35353535-aaaa-bbbb-cccc-464646464646"),
                            Channel = "Chat",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Intent = "CreateInvoice",
                            JurisdictionCode = "CA-ON",
                            LastMessageUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Locale = "en-CA",
                            Status = "Open",
                            Subject = "Create an Ontario monthly invoice",
                            SummaryJson = "{\"nextQuestion\":\"What tenant name should appear on the invoice?\"}",
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc")
                        },
                        new
                        {
                            Id = new Guid("37373737-aaaa-bbbb-cccc-484848484848"),
                            Channel = "Chat",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Intent = "CreateInvoice",
                            JurisdictionCode = "US-TX",
                            LastMessageUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Locale = "en-US",
                            Status = "Open",
                            Subject = "Create a Texas invoice draft",
                            SummaryJson = "{\"nextQuestion\":\"Which owner name should appear on the invoice?\"}",
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd")
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraInboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAttachments")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExternalMessageId")
                        .IsUnique();

                    b.ToTable("RuntiraInboxMessages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62626262-aaaa-bbbb-cccc-848484848484"),
                            Category = "Lead",
                            ClassificationJson = "{\"confidence\":0.92,\"suggestedAction\":\"CallBack\"}",
                            CreatedUtc = new DateTime(2026, 7, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            ExternalMessageId = "mock-ab-001",
                            FromEmail = "prospect.ab@example.com",
                            HasAttachments = true,
                            PreviewText = "Bonjour, je cherche un 2 chambres disponible en août à Calgary.",
                            Provider = "MockMicrosoft365",
                            ReceivedUtc = new DateTime(2026, 7, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            RelatedEntityId = new Guid("47474747-aaaa-bbbb-cccc-676767676767"),
                            RelatedEntityType = "Lead",
                            Status = "Classified",
                            Subject = "Disponibilité pour août",
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("64646464-aaaa-bbbb-cccc-868686868686"),
                            Category = "Invoice",
                            ClassificationJson = "{\"confidence\":0.88,\"suggestedAction\":\"SendInvoice\"}",
                            CreatedUtc = new DateTime(2026, 7, 3, 15, 0, 0, 0, DateTimeKind.Utc),
                            ExternalMessageId = "mock-on-001",
                            FromEmail = "resident.on@example.com",
                            HasAttachments = false,
                            PreviewText = "Can you resend the July invoice for unit 1204?",
                            Provider = "MockMicrosoft365",
                            ReceivedUtc = new DateTime(2026, 7, 3, 15, 0, 0, 0, DateTimeKind.Utc),
                            RelatedEntityId = new Guid("43434343-aaaa-bbbb-cccc-636363636363"),
                            RelatedEntityType = "Lease",
                            Status = "Classified",
                            Subject = "Need invoice copy for July",
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc")
                        },
                        new
                        {
                            Id = new Guid("66666666-aaaa-bbbb-cccc-888888888889"),
                            Category = "Document",
                            ClassificationJson = "{\"confidence\":0.81,\"suggestedAction\":\"ArchiveDocument\"}",
                            CreatedUtc = new DateTime(2026, 7, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            ExternalMessageId = "mock-tx-001",
                            FromEmail = "owner.tx@example.com",
                            HasAttachments = true,
                            PreviewText = "Attaching a quote for the next lease renewal package.",
                            Provider = "MockMicrosoft365",
                            ReceivedUtc = new DateTime(2026, 7, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            RelatedEntityId = new Guid("15151515-aaaa-bbbb-cccc-262626262626"),
                            RelatedEntityType = "Asset",
                            Status = "Classified",
                            Subject = "Please archive this vendor quote",
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd")
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraJurisdictionProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetRulesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceRulesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintenanceRulesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredQuestionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportedLanguagesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidationRulesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RuntiraJurisdictionProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12121212-aaaa-bbbb-cccc-343434343434"),
                            AssetRulesJson = "{\"supportsMultiUnit\":true}",
                            CountryCode = "CA",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceRulesJson = "{\"generatePdf\":true,\"addAutomaticSalesTax\":false}",
                            MaintenanceRulesJson = "{\"supportInboxClassification\":true}",
                            RegionCode = "AB",
                            RequiredQuestionsJson = "[\"propertyAddress\",\"billingPeriod\",\"monthlyRent\"]",
                            SupportedLanguagesJson = "[\"fr-CA\",\"en-CA\",\"es-MX\"]",
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb"),
                            ValidationRulesJson = "{\"billingPeriod\":{\"required\":true}}"
                        },
                        new
                        {
                            Id = new Guid("14141414-aaaa-bbbb-cccc-363636363636"),
                            AssetRulesJson = "{\"supportsMultiUnit\":true}",
                            CountryCode = "CA",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceRulesJson = "{\"generatePdf\":true,\"addAutomaticSalesTax\":false}",
                            MaintenanceRulesJson = "{\"supportInboxClassification\":true}",
                            RegionCode = "ON",
                            RequiredQuestionsJson = "[\"propertyAddress\",\"billingPeriod\",\"tenantName\",\"monthlyRent\"]",
                            SupportedLanguagesJson = "[\"en-CA\",\"fr-CA\"]",
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc"),
                            ValidationRulesJson = "{\"billingPeriod\":{\"required\":true},\"tenantName\":{\"required\":true}}"
                        },
                        new
                        {
                            Id = new Guid("16161616-aaaa-bbbb-cccc-383838383838"),
                            AssetRulesJson = "{\"supportsMultiUnit\":true}",
                            CountryCode = "US",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceRulesJson = "{\"generatePdf\":true,\"addAutomaticSalesTax\":false}",
                            MaintenanceRulesJson = "{\"supportInboxClassification\":true}",
                            RegionCode = "TX",
                            RequiredQuestionsJson = "[\"propertyAddress\",\"billingPeriod\",\"ownerName\",\"monthlyRent\"]",
                            SupportedLanguagesJson = "[\"en-US\",\"es-MX\"]",
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd"),
                            ValidationRulesJson = "{\"billingPeriod\":{\"required\":true},\"ownerName\":{\"required\":true}}"
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QualificationScore")
                        .HasColumnType("int");

                    b.Property<Guid?>("RuntiraOrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("RuntiraOrganizationId");

                    b.ToTable("RuntiraLeads");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47474747-aaaa-bbbb-cccc-676767676767"),
                            AssetId = new Guid("11111111-aaaa-bbbb-cccc-222222222222"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nora.bouchard@example.com",
                            FullName = "Nora Bouchard",
                            NotesJson = "{\"budget\":2500,\"moveInMonth\":\"2026-08\"}",
                            PhoneNumber = "+1-403-555-0171",
                            PreferredLanguage = "fr-CA",
                            QualificationScore = 92,
                            Source = "InboxMock",
                            Status = "Qualified",
                            Summary = "Lead chaud pour un 2 chambres avec entrée en août.",
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("49494949-aaaa-bbbb-cccc-696969696969"),
                            AssetId = new Guid("13131313-aaaa-bbbb-cccc-242424242424"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kevin.thompson@example.com",
                            FullName = "Kevin Thompson",
                            NotesJson = "{\"budget\":3200,\"petFriendly\":true}",
                            PhoneNumber = "+1-647-555-0112",
                            PreferredLanguage = "en-CA",
                            QualificationScore = 78,
                            Source = "ImportCsv",
                            Status = "New",
                            Summary = "Lead imported from listing export, interested in downtown condo.",
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc")
                        },
                        new
                        {
                            Id = new Guid("51515151-aaaa-bbbb-cccc-717171717171"),
                            AssetId = new Guid("15151515-aaaa-bbbb-cccc-262626262626"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "elena.perez@example.com",
                            FullName = "Elena Perez",
                            NotesJson = "{\"budget\":2900,\"preferredLanguage\":\"es-MX\"}",
                            PhoneNumber = "+1-214-555-0126",
                            PreferredLanguage = "es-MX",
                            QualificationScore = 84,
                            Source = "Manual",
                            Status = "Pending",
                            Summary = "Lead bilingue demandant un logement proche du centre-ville.",
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd")
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraLease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeaseEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LeaseStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TermsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("UnitId");

                    b.ToTable("RuntiraLeases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41414141-aaaa-bbbb-cccc-616161616161"),
                            AssetId = new Guid("11111111-aaaa-bbbb-cccc-222222222222"),
                            BillingPeriod = "Monthly",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaseEndUtc = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaseStartUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonthlyRent = 2450m,
                            ResidentId = new Guid("27272727-aaaa-bbbb-cccc-494949494949"),
                            Status = "Active",
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb"),
                            TermsJson = "{\"deposit\":2450}",
                            UnitId = new Guid("21212121-aaaa-bbbb-cccc-434343434343")
                        },
                        new
                        {
                            Id = new Guid("43434343-aaaa-bbbb-cccc-636363636363"),
                            AssetId = new Guid("13131313-aaaa-bbbb-cccc-242424242424"),
                            BillingPeriod = "Monthly",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaseEndUtc = new DateTime(2027, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaseStartUtc = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonthlyRent = 3100m,
                            ResidentId = new Guid("29292929-aaaa-bbbb-cccc-515151515151"),
                            Status = "Active",
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc"),
                            TermsJson = "{\"noticeDays\":60}",
                            UnitId = new Guid("23232323-aaaa-bbbb-cccc-454545454545")
                        },
                        new
                        {
                            Id = new Guid("45454545-aaaa-bbbb-cccc-656565656565"),
                            AssetId = new Guid("15151515-aaaa-bbbb-cccc-262626262626"),
                            BillingPeriod = "Monthly",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaseEndUtc = new DateTime(2027, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaseStartUtc = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonthlyRent = 2800m,
                            ResidentId = new Guid("31313131-aaaa-bbbb-cccc-535353535353"),
                            Status = "Active",
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd"),
                            TermsJson = "{\"lateFee\":75}",
                            UnitId = new Guid("25252525-aaaa-bbbb-cccc-474747474747")
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSelectedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("RuntiraMemberships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-1111-2222-3333-ffffffffffff"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Owner",
                            Status = "Active",
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb"),
                            UserId = new Guid("cccccccc-1111-2222-3333-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("efefefef-1111-2222-3333-f0f0f0f0f0f0"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Owner",
                            Status = "Active",
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc"),
                            UserId = new Guid("cccccccc-1111-2222-3333-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("f1f1f1f1-1111-2222-3333-f2f2f2f2f2f2"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Owner",
                            Status = "Active",
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd"),
                            UserId = new Guid("cccccccc-1111-2222-3333-dddddddddddd")
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RequiresAction")
                        .HasColumnType("bit");

                    b.Property<string>("StructuredPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("RuntiraMessages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-aaaa-bbbb-cccc-666666666666"),
                            AuthorType = "User",
                            Content = "Crée la facture PDF de juillet pour le 1180 17 Ave SW.",
                            ConversationId = new Guid("33333333-aaaa-bbbb-cccc-444444444444"),
                            CreatedByEmail = "michelfopa@gmail.com",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = "Incoming",
                            RequiresAction = true,
                            StructuredPayloadJson = "{\"intent\":\"CreateInvoice\"}",
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("57575757-aaaa-bbbb-cccc-686868686868"),
                            AuthorType = "User",
                            Content = "Create the July invoice for 25 Carlton Street.",
                            ConversationId = new Guid("35353535-aaaa-bbbb-cccc-464646464646"),
                            CreatedByEmail = "michelfopa@gmail.com",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = "Incoming",
                            RequiresAction = true,
                            StructuredPayloadJson = "{\"intent\":\"CreateInvoice\"}",
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc")
                        },
                        new
                        {
                            Id = new Guid("59595959-aaaa-bbbb-cccc-707070707070"),
                            AuthorType = "User",
                            Content = "Create the monthly invoice draft for 2400 McKinney Avenue.",
                            ConversationId = new Guid("37373737-aaaa-bbbb-cccc-484848484848"),
                            CreatedByEmail = "michelfopa@gmail.com",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = "Incoming",
                            RequiresAction = true,
                            StructuredPayloadJson = "{\"intent\":\"CreateInvoice\"}",
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd")
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalSettingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LegalProfileJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("RuntiraOrganizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb"),
                            AdditionalSettingsJson = "{\"tenantMode\":\"path\",\"archive\":\"blob\"}",
                            BillingPlan = "Trial",
                            CountryCode = "CA",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLocale = "fr-CA",
                            IsActive = true,
                            LegalProfileJson = "{\"jurisdiction\":\"CA-AB\",\"supports\":[\"fr-CA\",\"en-CA\",\"es-MX\"]}",
                            Name = "Runtira Demo Alberta",
                            OwnerEmail = "michelfopa@gmail.com",
                            RegionCode = "AB",
                            Slug = "demo-alberta",
                            StripeCustomerId = "",
                            StripeSubscriptionId = "",
                            TimeZone = "America/Edmonton"
                        },
                        new
                        {
                            Id = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc"),
                            AdditionalSettingsJson = "{\"tenantMode\":\"path\",\"archive\":\"blob\"}",
                            BillingPlan = "Trial",
                            CountryCode = "CA",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLocale = "en-CA",
                            IsActive = true,
                            LegalProfileJson = "{\"jurisdiction\":\"CA-ON\",\"supports\":[\"en-CA\",\"fr-CA\"]}",
                            Name = "Runtira Demo Ontario",
                            OwnerEmail = "michelfopa@gmail.com",
                            RegionCode = "ON",
                            Slug = "demo-ontario",
                            StripeCustomerId = "",
                            StripeSubscriptionId = "",
                            TimeZone = "America/Toronto"
                        },
                        new
                        {
                            Id = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd"),
                            AdditionalSettingsJson = "{\"tenantMode\":\"path\",\"archive\":\"blob\"}",
                            BillingPlan = "Trial",
                            CountryCode = "US",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultLocale = "en-US",
                            IsActive = true,
                            LegalProfileJson = "{\"jurisdiction\":\"US-TX\",\"supports\":[\"en-US\",\"es-MX\"]}",
                            Name = "Runtira Demo Texas",
                            OwnerEmail = "michelfopa@gmail.com",
                            RegionCode = "TX",
                            Slug = "demo-texas",
                            StripeCustomerId = "",
                            StripeSubscriptionId = "",
                            TimeZone = "America/Chicago"
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraQuotaPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EnforceHardLimit")
                        .HasColumnType("bit");

                    b.Property<int>("MaxActiveWorkflows")
                        .HasColumnType("int");

                    b.Property<int>("MaxAssets")
                        .HasColumnType("int");

                    b.Property<int>("MaxBlobStorageMb")
                        .HasColumnType("int");

                    b.Property<int>("MaxDocuments")
                        .HasColumnType("int");

                    b.Property<int>("MaxMonthlyAiRequests")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RuntiraQuotaPolicies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56565656-aaaa-bbbb-cccc-787878787878"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforceHardLimit = true,
                            MaxActiveWorkflows = 50,
                            MaxAssets = 100,
                            MaxBlobStorageMb = 2048,
                            MaxDocuments = 1000,
                            MaxMonthlyAiRequests = 5000,
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("58585858-aaaa-bbbb-cccc-808080808080"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforceHardLimit = true,
                            MaxActiveWorkflows = 50,
                            MaxAssets = 100,
                            MaxBlobStorageMb = 2048,
                            MaxDocuments = 1000,
                            MaxMonthlyAiRequests = 5000,
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc")
                        },
                        new
                        {
                            Id = new Guid("60606060-aaaa-bbbb-cccc-828282828282"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnforceHardLimit = true,
                            MaxActiveWorkflows = 50,
                            MaxAssets = 100,
                            MaxBlobStorageMb = 2048,
                            MaxDocuments = 1000,
                            MaxMonthlyAiRequests = 5000,
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd")
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraResident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email");

                    b.ToTable("RuntiraResidents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("27272727-aaaa-bbbb-cccc-494949494949"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "amelie.gagnon@example.com",
                            FullName = "Amelie Gagnon",
                            NotesJson = "{\"leaseIntent\":\"renewal\"}",
                            PhoneNumber = "+1-403-555-0147",
                            PreferredLanguage = "fr-CA",
                            Status = "Active",
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("29292929-aaaa-bbbb-cccc-515151515151"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lucas.martin@example.com",
                            FullName = "Lucas Martin",
                            NotesJson = "{\"preferredChannel\":\"email\"}",
                            PhoneNumber = "+1-416-555-0120",
                            PreferredLanguage = "en-CA",
                            Status = "Active",
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc")
                        },
                        new
                        {
                            Id = new Guid("31313131-aaaa-bbbb-cccc-535353535353"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maya.rodriguez@example.com",
                            FullName = "Maya Rodriguez",
                            NotesJson = "{\"moveInWindow\":\"2026-08\"}",
                            PhoneNumber = "+1-214-555-0191",
                            PreferredLanguage = "es-MX",
                            Status = "Active",
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd")
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MarketRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("TenantId", "AssetId", "UnitCode")
                        .IsUnique();

                    b.ToTable("RuntiraUnits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21212121-aaaa-bbbb-cccc-434343434343"),
                            AdditionalDataJson = "{\"bedrooms\":2}",
                            AssetId = new Guid("11111111-aaaa-bbbb-cccc-222222222222"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            MarketRent = 2450m,
                            Status = "Occupied",
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb"),
                            UnitCode = "A-101",
                            UnitType = "Apartment"
                        },
                        new
                        {
                            Id = new Guid("23232323-aaaa-bbbb-cccc-454545454545"),
                            AdditionalDataJson = "{\"bedrooms\":1}",
                            AssetId = new Guid("13131313-aaaa-bbbb-cccc-242424242424"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            MarketRent = 3100m,
                            Status = "Occupied",
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc"),
                            UnitCode = "1204",
                            UnitType = "Condo"
                        },
                        new
                        {
                            Id = new Guid("25252525-aaaa-bbbb-cccc-474747474747"),
                            AdditionalDataJson = "{\"bedrooms\":2}",
                            AssetId = new Guid("15151515-aaaa-bbbb-cccc-262626262626"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            MarketRent = 2800m,
                            Status = "Occupied",
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd"),
                            UnitCode = "8B",
                            UnitType = "Apartment"
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("RuntiraUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-1111-2222-3333-dddddddddddd"),
                            ClerkUserId = "runtira_demo_owner",
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "michelfopa@gmail.com",
                            FullName = "Michel Fopa",
                            IsActive = true,
                            IsSuperAdmin = true,
                            PreferredLanguage = "fr-CA"
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraWorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredQuestionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationSchemaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RuntiraWorkflowTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-aaaa-bbbb-cccc-888888888888"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Collecte les champs requis du profil CA-AB et prépare une facture PDF envoyable.",
                            IsActive = true,
                            Name = "Create invoice draft for CA-AB",
                            PromptTemplate = "Demande les champs requis par la juridiction active avant génération.",
                            RequiredQuestionsJson = "[\"propertyAddress\",\"billingPeriod\",\"monthlyRent\"]",
                            TenantId = new Guid("aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb"),
                            TriggerType = "CreateInvoice",
                            ValidationSchemaJson = "{\"monthlyRent\":{\"min\":1}}"
                        },
                        new
                        {
                            Id = new Guid("79797979-aaaa-bbbb-cccc-909090909090"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Collects the Ontario-required invoice fields before generation.",
                            IsActive = true,
                            Name = "Create invoice draft for CA-ON",
                            PromptTemplate = "Ask for tenant and billing details required by the active jurisdiction.",
                            RequiredQuestionsJson = "[\"propertyAddress\",\"billingPeriod\",\"tenantName\",\"monthlyRent\"]",
                            TenantId = new Guid("abababab-1111-2222-3333-bcbcbcbcbcbc"),
                            TriggerType = "CreateInvoice",
                            ValidationSchemaJson = "{\"monthlyRent\":{\"min\":1},\"tenantName\":{\"required\":true}}"
                        },
                        new
                        {
                            Id = new Guid("81818181-aaaa-bbbb-cccc-929292929292"),
                            CreatedUtc = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Collects the Texas-required invoice fields before generation.",
                            IsActive = true,
                            Name = "Create invoice draft for US-TX",
                            PromptTemplate = "Ask for owner, billing period and property details required by the active jurisdiction.",
                            RequiredQuestionsJson = "[\"propertyAddress\",\"billingPeriod\",\"ownerName\",\"monthlyRent\"]",
                            TenantId = new Guid("acacacac-1111-2222-3333-bdbdbdbdbdbd"),
                            TriggerType = "CreateInvoice",
                            ValidationSchemaJson = "{\"monthlyRent\":{\"min\":1},\"ownerName\":{\"required\":true}}"
                        });
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraAsset", b =>
                {
                    b.HasOne("Runtira.Domain.Entities.RuntiraOrganization", "Tenant")
                        .WithMany("Assets")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraAttachment", b =>
                {
                    b.HasOne("Runtira.Domain.Entities.RuntiraInboxMessage", "InboxMessage")
                        .WithMany("Attachments")
                        .HasForeignKey("InboxMessageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("InboxMessage");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraBlobArchive", b =>
                {
                    b.HasOne("Runtira.Domain.Entities.RuntiraOrganization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraConversation", b =>
                {
                    b.HasOne("Runtira.Domain.Entities.RuntiraOrganization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraJurisdictionProfile", b =>
                {
                    b.HasOne("Runtira.Domain.Entities.RuntiraOrganization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraLead", b =>
                {
                    b.HasOne("Runtira.Domain.Entities.RuntiraAsset", "Asset")
                        .WithMany("Leads")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Runtira.Domain.Entities.RuntiraOrganization", null)
                        .WithMany("Leads")
                        .HasForeignKey("RuntiraOrganizationId");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraLease", b =>
                {
                    b.HasOne("Runtira.Domain.Entities.RuntiraAsset", "Asset")
                        .WithMany("Leases")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Runtira.Domain.Entities.RuntiraResident", "Resident")
                        .WithMany("Leases")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Runtira.Domain.Entities.RuntiraUnit", "Unit")
                        .WithMany("Leases")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Resident");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraMembership", b =>
                {
                    b.HasOne("Runtira.Domain.Entities.RuntiraOrganization", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Runtira.Domain.Entities.RuntiraUser", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraMessage", b =>
                {
                    b.HasOne("Runtira.Domain.Entities.RuntiraConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraQuotaPolicy", b =>
                {
                    b.HasOne("Runtira.Domain.Entities.RuntiraOrganization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraUnit", b =>
                {
                    b.HasOne("Runtira.Domain.Entities.RuntiraAsset", "Asset")
                        .WithMany("Units")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraWorkflowTemplate", b =>
                {
                    b.HasOne("Runtira.Domain.Entities.RuntiraOrganization", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraAsset", b =>
                {
                    b.Navigation("Leads");

                    b.Navigation("Leases");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraInboxMessage", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraOrganization", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Leads");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraResident", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraUnit", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("Runtira.Domain.Entities.RuntiraUser", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
